"""initial schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
revision='0001_initial_schema'
down_revision=None
branch_labels=None
depends_on=None

def upgrade():
    user_role=sa.Enum('user','admin',name='user_role')
    deletion_status=sa.Enum('requested','completed','failed',name='deletion_status')
    audit_action=sa.Enum('register','login','logout','file_upload','file_download','file_delete','file_hashed','duplicate_detected',name='audit_action')
    op.create_table('users',sa.Column('id',sa.CHAR(32),primary_key=True),sa.Column('email',sa.String(255),nullable=False),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('role',user_role,nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.UniqueConstraint('email',name='uq_users_email'))
    op.create_index('ix_users_email','users',['email'],unique=True)
    op.create_table('files',sa.Column('id',sa.CHAR(32),primary_key=True),sa.Column('owner_id',sa.CHAR(32),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('original_filename',sa.String(255),nullable=False),sa.Column('stored_filename',sa.String(255),nullable=False),sa.Column('storage_path',sa.String(1024),nullable=False),sa.Column('mime_type',sa.String(255),nullable=False),sa.Column('extension',sa.String(20),nullable=False),sa.Column('size_bytes',sa.BigInteger(),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('is_protected',sa.Boolean(),nullable=False),sa.Column('uploaded_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.Column('deleted_at',sa.DateTime(timezone=True),nullable=True),sa.UniqueConstraint('stored_filename',name='uq_files_stored_filename'))
    for n,c in [('ix_files_owner_id','owner_id'),('ix_files_extension','extension'),('ix_files_status','status'),('ix_files_uploaded_at','uploaded_at')]: op.create_index(n,'files',[c])
    op.create_index('ix_files_owner_status','files',['owner_id','status']); op.create_index('ix_files_owner_uploaded_at','files',['owner_id','uploaded_at']); op.create_index('ix_files_owner_filename','files',['owner_id','original_filename'])
    op.create_table('file_hashes',sa.Column('id',sa.CHAR(32),primary_key=True),sa.Column('file_id',sa.CHAR(32),sa.ForeignKey('files.id',ondelete='CASCADE'),nullable=False),sa.Column('algorithm',sa.String(20),nullable=False),sa.Column('hash_value',sa.String(64),nullable=False),sa.Column('calculated_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.UniqueConstraint('file_id',name='uq_file_hash_file_id'))
    op.create_index('ix_file_hashes_file_id','file_hashes',['file_id'],unique=True); op.create_index('ix_file_hashes_hash_value','file_hashes',['hash_value'])
    op.create_table('file_metadata',sa.Column('id',sa.CHAR(32),primary_key=True),sa.Column('file_id',sa.CHAR(32),sa.ForeignKey('files.id',ondelete='CASCADE'),nullable=False),sa.Column('width',sa.Integer(),nullable=True),sa.Column('height',sa.Integer(),nullable=True),sa.Column('page_count',sa.Integer(),nullable=True),sa.Column('encoding',sa.String(100),nullable=True),sa.Column('metadata_json',sa.JSON(),nullable=True),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.UniqueConstraint('file_id',name='uq_file_metadata_file_id'))
    op.create_index('ix_file_metadata_file_id','file_metadata',['file_id'],unique=True)
    op.create_table('duplicate_groups',sa.Column('id',sa.CHAR(32),primary_key=True),sa.Column('file_id',sa.CHAR(32),sa.ForeignKey('files.id',ondelete='CASCADE'),nullable=False),sa.Column('group_hash',sa.String(64),nullable=False),sa.Column('is_original',sa.Boolean(),nullable=False),sa.Column('storage_consumed_bytes',sa.BigInteger(),nullable=False),sa.Column('potential_savings_bytes',sa.BigInteger(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False))
    op.create_index('ix_duplicate_groups_file_id','duplicate_groups',['file_id']); op.create_index('ix_duplicate_groups_group_hash','duplicate_groups',['group_hash']); op.create_index('ix_duplicate_groups_hash_original','duplicate_groups',['group_hash','is_original'])
    op.create_table('deletion_history',sa.Column('id',sa.CHAR(32),primary_key=True),sa.Column('file_id',sa.CHAR(32),sa.ForeignKey('files.id',ondelete='RESTRICT'),nullable=False),sa.Column('user_id',sa.CHAR(32),sa.ForeignKey('users.id',ondelete='RESTRICT'),nullable=False),sa.Column('filename',sa.String(255),nullable=False),sa.Column('size_bytes',sa.BigInteger(),nullable=False),sa.Column('status',deletion_status,nullable=False),sa.Column('reason',sa.String(500),nullable=True),sa.Column('deleted_at',sa.DateTime(timezone=True),nullable=True),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False))
    op.create_index('ix_deletion_history_file_id','deletion_history',['file_id']); op.create_index('ix_deletion_history_user_id','deletion_history',['user_id'])
    op.create_table('audit_logs',sa.Column('id',sa.CHAR(32),primary_key=True),sa.Column('user_id',sa.CHAR(32),sa.ForeignKey('users.id',ondelete='SET NULL'),nullable=True),sa.Column('file_id',sa.CHAR(32),sa.ForeignKey('files.id',ondelete='SET NULL'),nullable=True),sa.Column('action',audit_action,nullable=False),sa.Column('ip_address',sa.String(45),nullable=True),sa.Column('user_agent',sa.String(500),nullable=True),sa.Column('details',sa.JSON(),nullable=True),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False))
    op.create_index('ix_audit_logs_user_id','audit_logs',['user_id']); op.create_index('ix_audit_logs_file_id','audit_logs',['file_id']); op.create_index('ix_audit_logs_action','audit_logs',['action']); op.create_index('ix_audit_logs_created_at','audit_logs',['created_at'])

def downgrade():
    op.drop_table('audit_logs'); op.drop_table('deletion_history'); op.drop_table('duplicate_groups'); op.drop_table('file_metadata'); op.drop_table('file_hashes'); op.drop_table('files'); op.drop_table('users')
